### PR TITLE
Added "Republic of Kosovo"

### PR DESCRIPTION
**Pull request by itstyonirwansyah**
Inserted data of a country named "Republic of Kosovo"

### CODE REVIEW

**Comment by ecrmnn** [comment]
Hi @itstyonirwansyah 

Thanks for the PR.

Could you provide a few sources for this information?

I'm not up to date on this at all, but when I googled Kosovo, I found this;

> Kosovo is not listed as an ISO standard country. The unofficial 2 and 3-digit codes are used by the European Commission and others until Kosovo is assigned an ISO code.

**Comment by itstyonirwansyah** [comment]
I see that Kosovo is not listed as a standard country code, but will it be all right if you add the *temporary country code?

https://laendercode.net/en/2-letter-code/xk

https://www.dnb.com/content/dam/english/dnb-solutions/sales-and-marketing/iso_3digit_numeric_country_codes.xls

*The temporary country code is the one in the PR.

**Comment by ecrmnn** [comment]
Honestly, I personally wouldn't mind, but this package follows the [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) standard, hence the name of the package.

Since Republic of Kosovo is not part of this standard at the moment, I'll have to close this for now.

**Comment by itstyonirwansyah** [comment]
Hi @ecrmnn 

Thanks for letting me know about it, i hope you have nice day.

**Pull request closed without merging**
